/**
 * Pixel-art sprite frames for the guitar-playing Clawd.
 *
 * All frames share one canonical grid: sprite pixel (col,row) sits at
 * reference-px (SPRITE_ORIGIN.x + col*SPRITE_UNIT, SPRITE_ORIGIN.y + row*SPRITE_UNIT)
 * inside the 676x104 reference button. Frames were traced from the reference
 * recording (unit ≈ 2.9 source px) and cleaned up by hand.
 *
 * Palette keys:
 *   .  transparent        O  orange            o  orange shade
 *   E  eye                K  guitar black      k  guitar charcoal
 *   L  guitar lavender    l  lavender shadow   W  fret / highlight white
 */

export const SPRITE_UNIT = 2.9
export const SPRITE_ORIGIN = { x: 548, y: 1.8 }

export const PALETTE: Record<string, string> = {
  O: '#d8764f',
  o: '#b35c3d',
  E: '#1b1311',
  K: '#1f1b22',
  k: '#3b3642',
  L: '#8b88d8',
  l: '#6461a8',
  W: '#eeeaf6',
}

export type SpriteFrame = {
  rows: string[]
  dx: number
  dy: number
  /** top-centre and width of the head, when the frame's builder knows it (see cosmetics.headOf) */
  head?: { x: number; y: number; w: number }
}

/** Parse ascii art with an offset (in sprite px) into a frame. */
const f = (dx: number, dy: number, art: string): SpriteFrame => ({
  dx,
  dy,
  rows: art.replace(/^\n/, '').replace(/\n\s*$/, '').split('\n').map((r) => r.replace(/^\s*\|/, '')),
})

// ───────────────────────── intro: front-facing Clawd ─────────────────────────

export const FRONT_IDLE = f(4, 9, `
    |....OOOOOOOOOOOOOOOOO....
    |....OOOOOOOOOOOOOOOOO....
    |....OOEEOOOOOOOOOEEOO....
    |....OOEEOOOOOOOOOEEOO....
    |OOOOOOOOOOOOOOOOOOOOOOOOO
    |OOOOOOOOOOOOOOOOOOOOOOOOO
    |OOOOOOOOOOOOOOOOOOOOOOOOO
    |OOOOOOOOOOOOOOOOOOOOOOOOO
    |....OOOOOOOOOOOOOOOOO....
    |....OOOOOOOOOOOOOOOOO....
    |....OOOOOOOOOOOOOOOOO....
    |....OOOOOOOOOOOOOOOOO....
    |....OO..OO.....OO..OO....
    |....OO..OO.....OO..OO....
    |....OO..OO.....OO..OO....
    |....OO..OO.....OO..OO....
`)

/** Little bounce: body drops a pixel, legs compress, right arm swings down. */
export const FRONT_BOB = f(4, 10, `
    |....OOOOOOOOOOOOOOOOO....
    |....OOOOOOOOOOOOOOOOO....
    |....OOEEOOOOOOOOOEEOO....
    |....OOEEOOOOOOOOOEEOO....
    |OOOOOOOOOOOOOOOOOOOOO....
    |OOOOOOOOOOOOOOOOOOOOO....
    |OOOOOOOOOOOOOOOOOOOOOOOOO
    |OOOOOOOOOOOOOOOOOOOOOOOOO
    |....OOOOOOOOOOOOOOOOOOOOO
    |....OOOOOOOOOOOOOOOOOOOOO
    |....OOOOOOOOOOOOOOOOO....
    |....OOOOOOOOOOOOOOOOO....
    |....OO..OO.....OO..OO....
    |....OO..OO.....OO..OO....
    |....OO..OO.....OO..OO....
`)

/** Right arm drops to the side and a guitar headstock peeks out. */
export const FRONT_GUITAR_1 = f(4, 9, `
    |....OOOOOOOOOOOOOOOOO.......
    |....OOOOOOOOOOOOOOOOO.......
    |....OOEEOOOOOOOOOEEOO.......
    |....OOEEOOOOOOOOOEEOO.......
    |OOOOOOOOOOOOOOOOOOOOO.......
    |OOOOOOOOOOOOOOOOOOOOOK.K....
    |OOOOOOOOOOOOOOOOOOOOOLLLLl..
    |OOOOOOOOOOOOOOOOOOOOOkOO....
    |....OOOOOOOOOOOOOOOOOKOO....
    |....OOOOOOOOOOOOOOOOOkOO....
    |....OOOOOOOOOOOOOOOOO.......
    |....OOOOOOOOOOOOOOOOO.......
    |....OO..OO.....OO..OO.......
    |....OO..OO.....OO..OO.......
    |....OO..OO.....OO..OO.......
    |....OO..OO.....OO..OO.......
`)

/** Guitar lifted: neck angled up to the right from behind the body. */
export const FRONT_GUITAR_2 = f(4, 9, `
    |....OOOOOOOOOOOOOOOOO.......
    |....OOOOOOOOOOOOOOOOO.......
    |....OOEEOOOOOOOOOEEOO.......
    |....OOEEOOOOOOOOOEEOO...K.K.
    |OOOOOOOOOOOOOOOOOOOOO..LLLLl
    |OOOOOOOOOOOOOOOOOOOOO.KLl...
    |OOOOOOOOOOOOOOOOOOOOOKW.....
    |OOOOOOOOOOOOOOOOOOOOKK......
    |....OOOOOOOOOOOOOOOOOW......
    |....OOOOOOOOOOOOOOOOOOO.....
    |....OOOOOOOOOOOOOOOOOoO.....
    |....OOOOOOOOOOOOOOOOO.......
    |....OO..OO.....OO..OO.......
    |....OO..OO.....OO..OO.......
    |....OO..OO.....OO..OO.......
    |....OO..OO.....OO..OO.......
`)

/** Turned side-on, guitar held vertically in front of the body. */
export const SIDE_VERTICAL = f(8, 3, `
    |...................K.K.
    |..................LLLl.
    |..................KLl..
    |..................KW...
    |..................KK...
    |.................KW....
    |.................KK....
    |OOOOOOOOOOOOOO..KW.....
    |OOOOOOOOOOOOOO.KKK.....
    |OoEEOOOOOOOEEOKkW......
    |OoEEOOOOOOOEEKKKK......
    |OOOOOOOOOOOKKkKkKK.....
    |OOOOOOOOOOOKkLkLKk.....
    |OOOOOOOOOOOKLkkLkKk....
    |OOOOOOOOOOKKkLWkLKk....
    |OOOOOOOOOOKkLkLkkKO....
    |OOOOOOOOOOKLkkLkKkO....
    |OOOOOOOOOoKKkLkLKkk....
    |OOOOOOOOOKKKkkkKKkk....
    |OoOooooooKKKKKKKkk.....
    |Oo.OO...OOKKKKkkk......
    |Oo.OO...OO.KKkk........
    |Oo.OO...OO.............
`)

// ─────────────────────────── playing poses ───────────────────────────
// In the reference the guitar hardly moves while the body sways and turns
// behind it, so the playing poses are built from layers:
//   body (with eyes) → guitar → hands / right leg.

/** Merge layers (later layers paint over earlier ones) into one frame at (0,0). */
function compose(...layers: SpriteFrame[]): SpriteFrame {
  const W = 40
  const H = 30
  const grid = Array.from({ length: H }, () => Array<string>(W).fill('.'))
  for (const l of layers)
    l.rows.forEach((row, r) =>
      [...row].forEach((ch, c) => {
        const y = l.dy + r
        const x = l.dx + c
        if (ch !== '.' && y >= 0 && y < H && x >= 0 && x < W) grid[y][x] = ch
      }),
    )
  return { dx: 0, dy: 0, rows: grid.map((r) => r.join('')) }
}

/** Dark guitar, lavender face, checkered neck rising up-right, lavender headstock + two pegs. */
const GUITAR = f(13, 8, `
    |.............K.K
    |............LLLl
    |...........KLl..
    |..........KW....
    |.........KK.....
    |........KW......
    |...KKKkKK.......
    |...KKkKW........
    |...KKkKK........
    |...KKLLKK.......
    |...KkLLLK.......
    |...KLLWLLK......
    |KKKKLLLLLK......
    |KKKkkLLLK.......
    |KKKKKkLLK.......
    |KKKKKKLlK.......
    |.KKKKKKK........
    |..KKK...........
`)

/** Side-on body block: left edge + bottom row shaded. `eyes` is painted on top. */
function body(dx: number, w: number, eyes: [number, number, string][], leg: number, legRows = 4): SpriteFrame {
  const rows: string[] = []
  for (let r = 0; r < 11; r++) {
    const edge = r < 9 ? 'o' : r === 9 ? 'oo' : '.o'
    rows.push((edge + 'O'.repeat(w - edge.length)).slice(0, w))
  }
  rows[10] = '.' + 'o'.repeat(w - 1)
  for (const [ex, ey, ch] of eyes) {
    const row = [...rows[ey]]
    row[ex] = ch
    rows[ey] = row.join('')
  }
  for (let r = 0; r < legRows; r++) rows.push(' '.repeat(leg).replace(/ /g, '.') + 'oO')
  return { dx, dy: 10, rows }
}

const eye2 = (x: number, y: number): [number, number, string][] => [
  [x, y, 'E'],
  [x + 1, y, 'E'],
  [x, y + 1, 'E'],
  [x + 1, y + 1, 'E'],
]
const dash = (x: number, y: number): [number, number, string][] => [0, 1, 2].map((i) => [x + i, y, 'E'] as [number, number, string])

/** Fretting hand gripping the neck near the body. */
const HAND_LOW = f(21, 14, `
    |OO
    |oO
`)
/** Fretting hand slid up the neck (arm extended). */
const HAND_HIGH = f(21, 11, `
    |...OO
    |..OOo
    |.OO..
    |OO...
`)
const HAND_MID = f(21, 12, `
    |..OO
    |.OOo
    |OO..
`)
/** Picking hand over the strings: down / up. */
const PICK_DOWN = f(19, 20, `
    |OO
    |oO
`)
const PICK_UP = f(19, 17, `
    |OO
    |oO
`)
/** Right leg peeking out right of the guitar face. */
const LEG_R = f(22, 20, `
    |.O
    |oO
    |oO
    |oO
    |oO
`)

/** A1 – sway left, looking ahead (notes-above move). */
export const PLAY_A1 = compose(body(6, 15, [...eye2(1, 0), ...eye2(11, 0)], 2), GUITAR, HAND_LOW, LEG_R)
/** A2 – sway right, face turned toward the guitar. */
export const PLAY_A2 = compose(body(9, 15, [...eye2(4, 0), ...eye2(13, 0)], 1), GUITAR, HAND_LOW, LEG_R)
/** B1 – eyes squeezed shut, strum down (sparks move). */
export const PLAY_B1 = compose(body(7, 16, [...dash(4, 3), ...dash(13, 3)], 2), GUITAR, HAND_LOW, PICK_DOWN, LEG_R)
/** B2 – strum up. */
export const PLAY_B2 = compose(body(7, 16, [...dash(4, 3), ...dash(13, 3)], 2), GUITAR, HAND_LOW, PICK_UP, LEG_R)
/** C1 – eyes open, fretting hand high on the neck (headstock-notes move). */
export const PLAY_C1 = compose(body(7, 16, [...eye2(5, 2), ...eye2(14, 2)], 2), GUITAR, HAND_HIGH, PICK_DOWN, LEG_R)
/** C2 – hand slides back down between strums. */
export const PLAY_C2 = compose(body(7, 16, [...eye2(5, 2), ...eye2(14, 2)], 2), GUITAR, HAND_MID, PICK_UP, LEG_R)

/** Wind-up: leaning back, snout out front, guitar swung low and upright. */
export const WINDUP = f(3, 8, `
    |.......................K.K
    |......................LLLL
    |.....OOOOOOOOOOOOOO..KW...
    |....oOOOOOOOOOOOOOOOKK....
    |....oOEEOOOOOOOEEKKW......
    |OOOOoOEEOOOOOOKKKKK.......
    |OOOOOOOOOOOOOKKKooKKk.....
    |OOOOOOOOOOOOoKKKoKLkO.....
    |.OOOOOOOOOOoKKkKKOOO......
    |....OOOOOOOKKKLKKOO.......
    |.....oOOOoKKKKkLLk........
    |.....ooOoKKKKLLKLk........
    |.....oOOoKKKKLLLLkOO......
    |.....oOOoKKKkLLLkkOOo.....
    |.....oOooKKKKkLkkoOOo.....
    |......OK.KKKKkKkO..OO.....
    |......oK.kKKKKKOO..Oo.....
    |......oK.OoO...OO.........
`)

/** D1 – power chord: crouch-jump forward, guitar thrust out. */
export const POWER_1 = f(11, 10, `
    |..................LL...
    |..................kLLL.
    |.oOOOOOOOOOOOOOO.KW....
    |oOOOOOOOOOOOOOOOKK.....
    |oOOOEOOOOOOOOEKKK......
    |oOOOEOOOOOOOOKKKkK.....
    |oOOOOOOOOOOOKKoKKOO....
    |OOOOOOOOOOOOKKKKoo.....
    |OOOOOOOOOOOOLKKKk......
    |OOOOOOOOOOOKLLKKK......
    |oOOOOOOoOOOOKLLkLL.....
    |oOOOOOKoOOOOkLLLkK.....
    |oOooOOOOoOoOLLWKk......
    |ooO.OOOkkKkkOKLk.......
    |ooO.OO.KKKKKKLKk.......
    |.oo.OO..KKKKKOKk.......
    |..........kkk..........
`)

/** D2 – landing from the power chord, body squashed, neck high. */
export const POWER_2 = f(10, 9, `
    |......................K.K
    |.....................LLLL
    |....................KW...
    |.oOOOOOOOOOOOOOO...KK....
    |oOOOOOOOOOOOOOOOO.WK.....
    |oOOOEEOOOOOOOEEOOKK......
    |oOOOEEOOOOOOOEEKKK.......
    |oOOOOOOOOOOOOKKoKOO......
    |OOOOOOOOOOOOKKKKoOO......
    |OOOOOOOOOOOOKLKKk........
    |OOOOOOOOOOOKLLLKK........
    |oOOOOOOOOOOKLLWLkK.......
    |oOOOOOOOOOKLLLLLkK.......
    |oOooOOOOOKKKLLLKkOO......
    |ooO..KKKKKKKKLKkOOO......
    |ooO..KKKKKKKKKk..OO......
`)

export const FRAMES = {
  FRONT_IDLE,
  FRONT_BOB,
  FRONT_GUITAR_1,
  FRONT_GUITAR_2,
  SIDE_VERTICAL,
  PLAY_A1,
  PLAY_A2,
  PLAY_B1,
  PLAY_B2,
  PLAY_C1,
  PLAY_C2,
  WINDUP,
  POWER_1,
  POWER_2,
} as const

export type FrameName = keyof typeof FRAMES

// ─────────────────────────── particle glyphs ───────────────────────────
// Yellow / grey musical notes and spark dashes. `#` = filled pixel.

export const NOTE_GLYPHS: string[][] = [
  // eighth note ♪ (flag to the right)
  ['.##', '.#.', '##.'],
  // beamed pair ♫
  ['###', '#.#', '#.#'],
  // quarter-ish tick
  ['..#', '###', '#..'],
  // little flag
  ['##.', '.##', '.#.'],
]

export const GREY_NOTE_GLYPHS: string[][] = [
  // single eighth ♪, 3x5
  ['.#.', '.##', '.#.', '##.', '##.'],
  // beamed ♫, 5x5
  ['.####', '.#..#', '.#..#', '##.##', '##.##'],
]

export const SPARK_GLYPHS: string[][] = [
  ['##.', '.##'],
  ['###'],
  ['#..', '.##'],
  ['##', '.#'],
]
